
package mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiciosBDTU", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", wsdlLocation = "file:/C:/Users/admin/AppData/Local/Temp/tempdir5322616428742433982.tmp/ServiciosBDTU_Dictamen_1.wsdl")
public class ServiciosBDTU_Service
    extends Service
{

    private final static URL SERVICIOSBDTU_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu.ServiciosBDTU_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu.ServiciosBDTU_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/admin/AppData/Local/Temp/tempdir5322616428742433982.tmp/ServiciosBDTU_Dictamen_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/admin/AppData/Local/Temp/tempdir5322616428742433982.tmp/ServiciosBDTU_Dictamen_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICIOSBDTU_WSDL_LOCATION = url;
    }

    public ServiciosBDTU_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiciosBDTU_Service() {
        super(SERVICIOSBDTU_WSDL_LOCATION, new QName("http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", "ServiciosBDTU"));
    }

    /**
     * 
     * @return
     *     returns ServiciosBDTU
     */
    @WebEndpoint(name = "ServiciosBDTUPort")
    public ServiciosBDTU getServiciosBDTUPort() {
        return super.getPort(new QName("http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", "ServiciosBDTUPort"), ServiciosBDTU.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiciosBDTU
     */
    @WebEndpoint(name = "ServiciosBDTUPort")
    public ServiciosBDTU getServiciosBDTUPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", "ServiciosBDTUPort"), ServiciosBDTU.class, features);
    }

}
