
package mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ServiciosBDTU", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiciosBDTU {


    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu.ConsultaPersonaFisicaResponse
     */
    @WebMethod
    @WebResult(name = "consultaPersonaFisicaResponseParam", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
    public ConsultaPersonaFisicaResponse consultaPersonaFisica(
        @WebParam(name = "consultaPersonaFisicaRequestParam", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
        ConsultaPersonaFisica parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu.ConsultaPersonaMoralResponse
     */
    @WebMethod
    @WebResult(name = "consultaPersonaMoralResponseParam", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
    public ConsultaPersonaMoralResponse consultaPersonaMoral(
        @WebParam(name = "consultaPersonaMoralRequestParam", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
        ConsultaPersonaMoral parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu.ConsultaSolicitudResponse
     */
    @WebMethod
    @WebResult(name = "consultaSolicitudResponseParam", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
    public ConsultaSolicitudResponse consultaSolicitud(
        @WebParam(name = "consultaSolicitudRequestParam", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
        ConsultaSolicitud parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu.ConsultaSujetoObligadoResponse
     */
    @WebMethod
    @WebResult(name = "consultaSujetoObligadoResponseParam", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
    public ConsultaSujetoObligadoResponse consultaSujetoObligado(
        @WebParam(name = "consultaSujetoObligadoRequestParam", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
        ConsultaSujetoObligado parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns mx.gob.imss.cit.dictamen.servicios.ws.serviciosbdtu.ObtenerEstadoTramiteOutput
     */
    @WebMethod
    @WebResult(name = "obtenerEstadoTramiteResponse", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
    public ObtenerEstadoTramiteOutput obtenerEstadoTramite(
        @WebParam(name = "obtenerEstadoTramiteRequest", targetNamespace = "http://servicios.dictamen.cit.imss.gob.mx/ws/ServiciosBDTU/", partName = "parameters")
        ObtenerEstadoTramiteInput parameters);

}
